package com.ff7damage;

public enum Events {
	CHARACTER_CHANGED,
	UPDATE_CENTER_PANEL,
	SENDING_CENTER_PANEL_DATA,
	PLEASE_SEND_RIGHT_PANEL_DATA,
	SENDING_RIGHT_PANEL_DATA,
	DATA_FOR_MODEL,
	RESULT_FOR_CONTROLLER,
	RESULT_FOR_VIEW
}